<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<AnalysisLevel>latest-minimum</AnalysisLevel>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="10.0.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.StringTools" Version="18.9.6" ExcludeAssets="runtime" PrivateAssets="all">
			<IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.9.0" />
		<PackageReference Include="ModelContextProtocol" Version="2.2.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
		<PackageReference Include="NUnit" Version="5.0.0-beta.1" />
		<PackageReference Include="NUnit.Analyzers" Version="4.14.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="NUnit.Framework" />
		<Using Include="RoslynSentinel.Advanced" />
		<Using Include="RoslynSentinel.Basic" />
		<Using Include="RoslynSentinel.Common" />
		<Using Include="RoslynSentinel.Server.Basic" />
		<Using Include="RoslynSentinel.Server.Advanced" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RoslynSentinel.Advanced\RoslynSentinel.Advanced.csproj" />
		<ProjectReference Include="..\RoslynSentinel.Basic\RoslynSentinel.Basic.csproj" />
		<ProjectReference Include="..\RoslynSentinel.Common\RoslynSentinel.Common.csproj" />
		<ProjectReference Include="..\RoslynSentinel.Server.Basic\RoslynSentinel.Server.Basic.csproj" />
		<ProjectReference Include="..\RoslynSentinel.Server.Advanced\RoslynSentinel.Server.Advanced.csproj" />
		<ProjectReference Include="..\RoslynSentinel.Tests\RoslynSentinel.Tests.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<!-- Prevents static code analysis rules from running on this project -->
		<RunCodeAnalysis>false</RunCodeAnalysis>
		<!-- If using specific .NET code analysis metrics tools -->
		<IsCodeAnalysisAnalyzersExecuted>false</IsCodeAnalysisAnalyzersExecuted>
	</PropertyGroup>

</Project>
