using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace RoslynSentinel.Engines.Basic;

/// <summary>Options for <see cref="NamedArgumentsEngine"/>.</summary>
/// <param name="MinParameters">Only calls to methods declaring at least this many parameters are rewritten.</param>
/// <param name="LiteralArgumentsOnly">When true, only literal arguments (true, null, 0, "text", default) get a name; other arguments are left positional.</param>
public sealed record NamedArgumentsOptions(int MinParameters = 2, bool LiteralArgumentsOnly = false);

/// <summary>The rewritten root plus counters describing what changed.</summary>
public sealed record NamedArgumentsRewriteResult(SyntaxNode Root, int CallSitesConverted, int ArgumentsNamed);

/// <summary>Per-file counts for one rewritten file.</summary>
public sealed record NamedArgumentsFileSummary(string FilePath, int CallSites, int Arguments);

/// <summary>New text for every changed file (keyed by path), per-file counts, or an error.</summary>
public sealed record NamedArgumentsOutcome(Dictionary<FilePathWrapper, string> Changes, IReadOnlyList<NamedArgumentsFileSummary> Files, ResultError? Error);

/// <summary>
/// Converts positional arguments to named arguments at call sites, resolved semantically.
/// Unlike the RequireNamedArgs analyzer it does not need the target method to carry an attribute.
/// Covers invocations, object creation (explicit and target-typed), attribute arguments, and
/// <c>: this(...)</c> / <c>: base(...)</c> initializers, including primary-constructor base types.
/// </summary>
public sealed class NamedArgumentsEngine
{
    private readonly IWorkspaceManager _workspaceManager;

    public NamedArgumentsEngine(IWorkspaceManager workspaceManager)
    {
        _workspaceManager = workspaceManager;
    }

    /// <summary>
    /// Computes the rewrite for a scope without writing anything. <paramref name="scopeName"/> is a project name for
    /// <see cref="NamedArgumentsScope.project"/> and an absolute file path for <see cref="NamedArgumentsScope.file"/>.
    /// <paramref name="targetSymbol"/> (a method or constructor docCommentId) restricts the rewrite to calls of that one method.
    /// </summary>
    public async Task<NamedArgumentsOutcome> ConvertAsync(NamedArgumentsScope scope, string? scopeName, string? targetSymbol, NamedArgumentsOptions options, CancellationToken cancellationToken = default)
    {
        var solution = await _workspaceManager.GetSolutionAsync(ReadSource.Committed, cancellationToken);

        var (documents, scopeError) = SelectDocuments(solution, scope, scopeName);
        if (scopeError is not null)
        {
            return Failed(scopeError);
        }

        string? targetDocCommentId = null;
        if (!string.IsNullOrWhiteSpace(targetSymbol))
        {
            var (resolvedId, targetError) = await ResolveTargetAsync(solution, targetSymbol, cancellationToken);
            if (targetError is not null)
            {
                return Failed(targetError);
            }

            targetDocCommentId = resolvedId;
        }

        var changes = new Dictionary<FilePathWrapper, string>();
        var files = new List<NamedArgumentsFileSummary>();
        // A file linked into several projects (e.g. multi-targeting) shows up once per project; rewrite it once.
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var document in documents)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (document.FilePath is null || IsGeneratedPath(document.FilePath) || !seen.Add(document.FilePath))
            {
                continue;
            }

            var root = await document.GetSyntaxRootAsync(cancellationToken);
            var semanticModel = await document.GetSemanticModelAsync(cancellationToken);
            if (root is null || semanticModel is null || HasAutoGeneratedHeader(root))
            {
                continue;
            }

            var result = Rewrite(semanticModel, root, options, targetDocCommentId, cancellationToken);
            if (result.CallSitesConverted == 0)
            {
                continue;
            }

            changes[new FilePathWrapper(document.FilePath)] = result.Root.ToFullString();
            files.Add(new NamedArgumentsFileSummary(document.FilePath, result.CallSitesConverted, result.ArgumentsNamed));
        }

        return new NamedArgumentsOutcome(changes, files, null);
    }

    /// <summary>
    /// Pure rewrite over one syntax tree. <paramref name="root"/> must belong to the tree that
    /// <paramref name="semanticModel"/> was created for. <paramref name="targetDocCommentId"/>, when set, limits the
    /// rewrite to calls of the method with that declaration id.
    /// </summary>
    public static NamedArgumentsRewriteResult Rewrite(SemanticModel semanticModel, SyntaxNode root, NamedArgumentsOptions options, string? targetDocCommentId = null, CancellationToken cancellationToken = default)
    {
        var rewriter = new NamedArgumentsRewriter(semanticModel, options, targetDocCommentId, cancellationToken);
        var newRoot = rewriter.Visit(root)!;
        return new NamedArgumentsRewriteResult(newRoot, rewriter.CallSitesConverted, rewriter.ArgumentsNamed);
    }

    private static NamedArgumentsOutcome Failed(ResultError error)
    {
        return new NamedArgumentsOutcome(new Dictionary<FilePathWrapper, string>(), [], error);
    }

    private static (IReadOnlyList<Document> Documents, ResultError? Error) SelectDocuments(Solution solution, NamedArgumentsScope scope, string? scopeName)
    {
        switch (scope)
        {
            case NamedArgumentsScope.solution:
                return (solution.Projects.SelectMany(p => p.Documents).ToList(), null);

            case NamedArgumentsScope.project:
            {
                if (string.IsNullOrWhiteSpace(scopeName))
                {
                    return ([], new ResultError(ToolErrorCode.InvalidArgument, "scope 'project' requires scopeName = the project name."));
                }

                var projects = solution.Projects.Where(p => string.Equals(p.Name, scopeName, StringComparison.OrdinalIgnoreCase)).ToList();
                if (projects.Count == 0)
                {
                    var available = string.Join(", ", solution.Projects.Select(p => p.Name).Distinct().Take(25));
                    return ([], new ResultError(ToolErrorCode.NotFound, $"No project named '{scopeName}'. Available projects: {available}."));
                }

                return (projects.SelectMany(p => p.Documents).ToList(), null);
            }

            case NamedArgumentsScope.file:
            {
                if (string.IsNullOrWhiteSpace(scopeName))
                {
                    return ([], new ResultError(ToolErrorCode.InvalidArgument, "scope 'file' requires scopeName = the file path."));
                }

                var wanted = new FilePathWrapper(scopeName);
                var matches = solution.Projects.SelectMany(p => p.Documents).Where(d => d.FilePath is not null && wanted.Equals(d.FilePath)).ToList();
                if (matches.Count == 0)
                {
                    return ([], new ResultError(ToolErrorCode.NotFound, $"File '{scopeName}' is not part of the loaded solution."));
                }

                return (matches, null);
            }

            default:
                return ([], new ResultError(ToolErrorCode.InvalidArgument, $"Unknown scope '{scope}'. Use solution, project or file."));
        }
    }

    private static async Task<(string? DocCommentId, ResultError? Error)> ResolveTargetAsync(Solution solution, string targetSymbol, CancellationToken cancellationToken)
    {
        foreach (var project in solution.Projects)
        {
            var compilation = await project.GetCompilationAsync(cancellationToken);
            var symbol = compilation is null ? null : DocumentationCommentId.GetFirstSymbolForDeclarationId(targetSymbol, compilation);
            if (symbol is null)
            {
                continue;
            }

            if (symbol is not IMethodSymbol method)
            {
                return (null, new ResultError(ToolErrorCode.InvalidArgument, $"targetSymbol must identify a method or constructor, but '{targetSymbol}' is a {symbol.Kind.ToString().ToLowerInvariant()}. Pass a docCommentId starting with 'M:'."));
            }

            return (DocumentationCommentId.CreateDeclarationId(method.OriginalDefinition), null);
        }

        return (null, new ResultError(ToolErrorCode.NotFound, $"No symbol found for targetSymbol docCommentId: {targetSymbol}"));
    }

    private static bool IsGeneratedPath(string path)
    {
        var name = Path.GetFileName(path);
        if (name.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || name.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
            || name.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || name.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        var objSegment = Path.DirectorySeparatorChar + "obj" + Path.DirectorySeparatorChar;
        return path.Contains(objSegment, StringComparison.OrdinalIgnoreCase);
    }

    private static bool HasAutoGeneratedHeader(SyntaxNode root)
    {
        foreach (var trivia in root.GetLeadingTrivia())
        {
            if (trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) || trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
            {
                if (trivia.ToString().Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }
        }

        return false;
    }

    private sealed class NamedArgumentsRewriter : CSharpSyntaxRewriter
    {
        /// <summary>The parts of one argument the naming decision depends on, shared by call and attribute argument lists.</summary>
        private readonly record struct ArgumentView(string? ExistingName, bool IsPropertySetter, ExpressionSyntax Expression);

        private readonly SemanticModel _semanticModel;
        private readonly NamedArgumentsOptions _options;
        private readonly string? _targetDocCommentId;
        private readonly CancellationToken _cancellationToken;

        public int CallSitesConverted { get; private set; }

        public int ArgumentsNamed { get; private set; }

        public NamedArgumentsRewriter(SemanticModel semanticModel, NamedArgumentsOptions options, string? targetDocCommentId, CancellationToken cancellationToken)
        {
            _semanticModel = semanticModel;
            _options = options;
            _targetDocCommentId = targetDocCommentId;
            _cancellationToken = cancellationToken;
        }

        public override SyntaxNode? VisitInvocationExpression(InvocationExpressionSyntax node)
        {
            var visited = (InvocationExpressionSyntax)base.VisitInvocationExpression(node)!;
            var list = NameArguments(node, node.ArgumentList, visited.ArgumentList);
            return list is null ? visited : visited.WithArgumentList(list);
        }

        public override SyntaxNode? VisitObjectCreationExpression(ObjectCreationExpressionSyntax node)
        {
            var visited = (ObjectCreationExpressionSyntax)base.VisitObjectCreationExpression(node)!;
            var list = NameArguments(node, node.ArgumentList, visited.ArgumentList);
            return list is null ? visited : visited.WithArgumentList(list);
        }

        public override SyntaxNode? VisitImplicitObjectCreationExpression(ImplicitObjectCreationExpressionSyntax node)
        {
            var visited = (ImplicitObjectCreationExpressionSyntax)base.VisitImplicitObjectCreationExpression(node)!;
            var list = NameArguments(node, node.ArgumentList, visited.ArgumentList);
            return list is null ? visited : visited.WithArgumentList(list);
        }

        public override SyntaxNode? VisitConstructorInitializer(ConstructorInitializerSyntax node)
        {
            var visited = (ConstructorInitializerSyntax)base.VisitConstructorInitializer(node)!;
            var list = NameArguments(node, node.ArgumentList, visited.ArgumentList);
            return list is null ? visited : visited.WithArgumentList(list);
        }

        public override SyntaxNode? VisitPrimaryConstructorBaseType(PrimaryConstructorBaseTypeSyntax node)
        {
            var visited = (PrimaryConstructorBaseTypeSyntax)base.VisitPrimaryConstructorBaseType(node)!;
            var list = NameArguments(node, node.ArgumentList, visited.ArgumentList);
            return list is null ? visited : visited.WithArgumentList(list);
        }

        public override SyntaxNode? VisitAttribute(AttributeSyntax node)
        {
            var visited = (AttributeSyntax)base.VisitAttribute(node)!;
            var list = NameAttributeArguments(node, node.ArgumentList, visited.ArgumentList);
            return list is null ? visited : visited.WithArgumentList(list);
        }

        /// <summary>
        /// Returns the argument list with names added, or null when nothing should change.
        /// <paramref name="original"/> and <paramref name="originalList"/> come from the unmodified tree (needed for
        /// semantic lookups); <paramref name="visitedList"/> is the same list after nested calls were rewritten, so
        /// it has identical argument count and order.
        /// </summary>
        private ArgumentListSyntax? NameArguments(SyntaxNode original, ArgumentListSyntax? originalList, ArgumentListSyntax? visitedList)
        {
            if (originalList is null || visitedList is null)
            {
                return null;
            }

            var views = originalList.Arguments
                .Select(a => new ArgumentView(a.NameColon?.Name.Identifier.ValueText, false, a.Expression))
                .ToList();
            var names = PlanNames(original, views);
            if (names is null)
            {
                return null;
            }

            var visitedArgs = visitedList.Arguments;
            var newArgs = visitedArgs.Select((a, i) => names[i] is { } name ? WithName(a, name) : a).ToList();
            return visitedList.WithArguments(SyntaxFactory.SeparatedList(newArgs, visitedArgs.GetSeparators()));
        }

        private AttributeArgumentListSyntax? NameAttributeArguments(SyntaxNode original, AttributeArgumentListSyntax? originalList, AttributeArgumentListSyntax? visitedList)
        {
            if (originalList is null || visitedList is null)
            {
                return null;
            }

            var views = originalList.Arguments
                .Select(a => new ArgumentView(a.NameColon?.Name.Identifier.ValueText, a.NameEquals is not null, a.Expression))
                .ToList();
            var names = PlanNames(original, views);
            if (names is null)
            {
                return null;
            }

            var visitedArgs = visitedList.Arguments;
            var newArgs = visitedArgs.Select((a, i) => names[i] is { } name ? WithName(a, name) : a).ToList();
            return visitedList.WithArguments(SyntaxFactory.SeparatedList(newArgs, visitedArgs.GetSeparators()));
        }

        /// <summary>
        /// Decides which arguments get which parameter name. Returns one slot per argument (null = leave as is), or null
        /// when the call is out of scope or nothing would change. Counts the call site and named arguments when it plans a change.
        /// </summary>
        private string?[]? PlanNames(SyntaxNode original, IReadOnlyList<ArgumentView> args)
        {
            if (args.Count == 0)
            {
                return null;
            }

            if (_semanticModel.GetSymbolInfo(original, _cancellationToken).Symbol is not IMethodSymbol method || !IsSupportedKind(method.MethodKind))
            {
                return null;
            }

            if (_targetDocCommentId is not null && DocumentationCommentId.CreateDeclarationId((method.ReducedFrom ?? method).OriginalDefinition) != _targetDocCommentId)
            {
                return null;
            }

            var parameters = method.Parameters;
            var positionalCount = args.Count(a => !a.IsPropertySetter);
            if (parameters.Length == 0 || parameters.Length < _options.MinParameters || positionalCount > parameters.Length)
            {
                return null;
            }

            // Whether a call binds to the params array in normal or expanded form is not decidable from syntax alone,
            // so a params method is never rewritten (same stance as the RequireNamedArgs analyzer).
            if (parameters[^1].IsParams || IsInsideExpressionTree(original))
            {
                return null;
            }

            var names = new string?[args.Count];
            var named = 0;
            var positionalStillInOrder = true;

            for (var i = 0; i < args.Count; i++)
            {
                var arg = args[i];
                if (arg.IsPropertySetter)
                {
                    // Attribute property setters (Prop = value) always follow the constructor arguments.
                    continue;
                }

                if (arg.ExistingName is not null)
                {
                    // A named argument that is out of position makes any later positional argument invalid.
                    if (arg.ExistingName != parameters[i].Name)
                    {
                        positionalStillInOrder = false;
                    }

                    continue;
                }

                if (!positionalStillInOrder || !ShouldName(arg.Expression))
                {
                    continue;
                }

                names[i] = parameters[i].Name;
                named++;
            }

            if (named == 0)
            {
                return null;
            }

            CallSitesConverted++;
            ArgumentsNamed += named;
            return names;
        }

        private bool ShouldName(ExpressionSyntax expression)
        {
            return !_options.LiteralArgumentsOnly || IsLiteral(expression);
        }

        private static bool IsLiteral(ExpressionSyntax expression)
        {
            return expression switch
            {
                LiteralExpressionSyntax => true,
                DefaultExpressionSyntax => true,
                ParenthesizedExpressionSyntax parenthesized => IsLiteral(parenthesized.Expression),
                PrefixUnaryExpressionSyntax unary when unary.IsKind(SyntaxKind.UnaryMinusExpression) || unary.IsKind(SyntaxKind.UnaryPlusExpression) => unary.Operand is LiteralExpressionSyntax,
                _ => false
            };
        }

        private static bool IsSupportedKind(MethodKind kind)
        {
            return kind is MethodKind.Ordinary or MethodKind.Constructor or MethodKind.LocalFunction or MethodKind.ReducedExtension;
        }

        // Named arguments are illegal in expression trees (CS0853).
        private bool IsInsideExpressionTree(SyntaxNode node)
        {
            foreach (var lambda in node.Ancestors().OfType<LambdaExpressionSyntax>())
            {
                var converted = _semanticModel.GetTypeInfo(lambda, _cancellationToken).ConvertedType;
                if (converted?.OriginalDefinition.ToDisplayString() == "System.Linq.Expressions.Expression<TDelegate>")
                {
                    return true;
                }
            }

            return false;
        }

        private static NameColonSyntax BuildNameColon(string parameterName, SyntaxTriviaList leading)
        {
            // Reserved keywords (e.g. a parameter named "event") need an @ prefix to be written as an argument name.
            var text = SyntaxFacts.GetKeywordKind(parameterName) != SyntaxKind.None ? "@" + parameterName : parameterName;
            return SyntaxFactory.NameColon(SyntaxFactory.IdentifierName(text))
                .WithColonToken(SyntaxFactory.Token(SyntaxKind.ColonToken).WithTrailingTrivia(SyntaxFactory.Space))
                .WithLeadingTrivia(leading);
        }

        private static ArgumentSyntax WithName(ArgumentSyntax arg, string parameterName)
        {
            var nameColon = BuildNameColon(parameterName, arg.GetLeadingTrivia());
            return arg.WithLeadingTrivia(SyntaxTriviaList.Empty).WithNameColon(nameColon);
        }

        private static AttributeArgumentSyntax WithName(AttributeArgumentSyntax arg, string parameterName)
        {
            var nameColon = BuildNameColon(parameterName, arg.GetLeadingTrivia());
            return arg.WithLeadingTrivia(SyntaxTriviaList.Empty).WithNameColon(nameColon);
        }
    }
}
