using System.ComponentModel;

using Microsoft.Extensions.Logging;

using ModelContextProtocol;
using ModelContextProtocol.Server;

namespace RoslynSentinel.Server.Advanced;

[McpServerToolType]
public class SentinelCommentingTools
{
    private readonly CommentingEngine _commentingEngine;
    private readonly IWorkspaceManager _workspaceManager;
    private readonly ILogger<SentinelCommentingTools> _logger;

    private const int DefaultMaxMembers = 200;
    private const int DefaultMaxTokens = 2000;

    public SentinelCommentingTools(
        CommentingEngine commentingEngine,
        IWorkspaceManager workspaceManager,
        ILogger<SentinelCommentingTools> logger)
    {
        _commentingEngine = commentingEngine;
        _workspaceManager = workspaceManager;
        _logger = logger;
    }

    [McpServerTool(Name = "BulkComment")]
    [Description("""
        Adds or refreshes /// <summary> doc comments across a solution, project, or file, tracking
        per-member completion via [ContentHash] so repeated calls resume for free and never
        re-process unchanged members. Comment prose is generated by a locally-hosted LLM (LM
        Studio, OpenAI-compatible endpoint) called by the server itself — the caller just invokes
        this tool, repeated a handful of times, instead of walking the tree itself.

        scope: solution (default) | project | file.
          project — restrict to one project; projectName required.
          file    — restrict to a single file; filePath required.
        dryRun: report planned work without calling the LLM or writing any changes.
        maxMembers: cap on members processed (LLM + write) in this call (default 200) — re-invoke
          to continue; already-commented members are skipped automatically on the next call because
          their [ContentHash] already matches.
        maxRuntimeSeconds: optional wall-clock cap on the work phase (0 = unbounded, capped only by
          maxMembers).

        Every call always runs the seed phase first (mechanical, no LLM): any member with no
        [ContentHash("Comment", ...)] at all gets stamped with a sentinel hash. This is what makes
        remaining work a queryable fact — CommentingResult.RemainingStale reports how many members
        are still stale after this call, independent of any prior conversation state.

        Returns CommentingResult: TotalMembers/AlreadyCurrent/Seeded/CommentedThisCall/
        RemainingStale counts, per-file breakdown, Skipped items with reasons. This return value —
        not agent prose — is the authoritative completion signal for the run. RemainingStale > 0
        means call BulkComment again with the same scope to continue.
        """)]
    public async Task<ToolResult<CommentingResult>> BulkComment(
        ToolScope scope = ToolScope.solution,
        string? projectName = null,
        string? filePath = null,
        bool dryRun = false,
        int maxMembers = DefaultMaxMembers,
        int maxRuntimeSeconds = 0,
        RequestContext<CallToolRequestParams>? requestParams = null,
        CancellationToken cancellationToken = default)
    {
        if (_workspaceManager.CurrentSolution == null)
        {
            return new ToolResult<CommentingResult>
            {
                Success = false,
                Error = new ResultError(MigrationErrorCode.SolutionNotLoaded,
                    "No solution is loaded. Call load_solution first.")
            };
        }

        if (scope == ToolScope.project && string.IsNullOrEmpty(projectName))
        {
            return new ToolResult<CommentingResult>
            {
                Success = false,
                Error = new ResultError(MigrationErrorCode.InvalidArgument, "projectName is required when scope=project.")
            };
        }

        if (scope == ToolScope.file && string.IsNullOrEmpty(filePath))
        {
            return new ToolResult<CommentingResult>
            {
                Success = false,
                Error = new ResultError(MigrationErrorCode.InvalidArgument, "filePath is required when scope=file.")
            };
        }

        var halt = _workspaceManager.CheckBreaker();
        if (halt != null)
        {
            return new ToolResult<CommentingResult>
            {
                Success = false,
                Error = new ResultError(MigrationErrorCode.Exception,
                    $"Circuit breaker is open: {halt.Directive}")
            };
        }

        try
        {
            var result = await RunAsync(scope, projectName, filePath, dryRun, maxMembers, maxRuntimeSeconds, cancellationToken);
            return new ToolResult<CommentingResult> { Success = true, Data = result };
        }
        catch (Exception ex)
        {
            return new ToolResult<CommentingResult>
            {
                Success = false,
                Error = ToolErrorMapper.ToResultError(ex, _workspaceManager, "BulkComment")
            };
        }
    }

    private async Task<CommentingResult> RunAsync(
        ToolScope scope, string? projectName, string? filePath, bool dryRun, int maxMembers, int maxRuntimeSeconds, CancellationToken cancellationToken)
    {
        var changeId = Guid.NewGuid().ToString("N")[..8];
        var items = new List<OperationItemRecord>();
        var byFile = new Dictionary<FilePath, CommentingFileBreakdown>();
        var skipped = new List<FailureDetail>();

        CommentingFileBreakdown FileRow(FilePath path)
        {
            if (!byFile.TryGetValue(path, out var row))
            {
                byFile[path] = row = new CommentingFileBreakdown { filePath = path };
            }

            return row;
        }

        // ── Phase 1: seed (always runs, mechanical, no LLM) ─────────────────
        var (seedChanges, seededCount, alreadyTaggedAtSeedTime) = await _commentingEngine.SeedContentHashesAsync(
            scope, projectName, filePath, cancellationToken);

        if (seedChanges.Count > 0 && !dryRun)
        {
            var seedApply = await _workspaceManager.ApplyProposedChangesAsync(seedChanges, validateChanges: true, cancellationToken: cancellationToken);
            if (!seedApply.Success && seedApply.ValidationResult != null)
            {
                _logger.LogWarning("BulkComment: validation found {Count} error(s) in seed-phase changes",
                    seedApply.ValidationResult.Diagnostics.Count);
            }
        }

        foreach (var path in seedChanges.Keys)
        {
            FileRow(path).Seeded++;
        }

        // ── Phase 2: find stale members. When dryRun, the seed-phase changes were never applied,
        // so this walk sees the pre-seed workspace — every never-tagged member is (correctly)
        // reported as stale/planned work, same as a real run would find before seeding lands. ──
        var staleMembers = await _commentingEngine.FindStaleMembersAsync(scope, projectName, filePath, cancellationToken);

        // Members with no [ContentHash] at all show up in both seededCount (this call's seed pass)
        // and staleMembers (they're maximally stale) — total scope size is the union of "already
        // tagged before this call" and "newly seeded this call".
        int totalMembers = alreadyTaggedAtSeedTime + seededCount;
        int alreadyCurrentCount = totalMembers - staleMembers.Count;

        if (dryRun)
        {
            return new CommentingResult
            {
                TotalMembers = totalMembers,
                AlreadyCurrent = alreadyCurrentCount,
                Seeded = seededCount,
                CommentedThisCall = 0,
                RemainingStale = staleMembers.Count,
                Skipped = staleMembers.Select(m => new FailureDetail
                {
                    FilePath = m.FilePath,
                    MethodName = m.MemberName,
                    Reason = "dry_run",
                    Outcome = ItemRecordOutcome.Skipped,
                }).ToList(),
                ByFile = byFile.Values.ToList(),
                Severity = "ok",
                BreakerOpen = false,
                DryRun = true,
            };
        }

        // ── Phase 2: comment stale members, up to maxMembers / maxRuntimeSeconds ──
        // Applied per-file, not per-member: BulkComment operates at file granularity (one disk
        // write per file, covering every stale member that file had), unlike the *Async* migration
        // tools which apply per-member because a single member's edit there can touch multiple
        // files. Grouping preserves each file's original stale-member order.
        var deadline = maxRuntimeSeconds > 0 ? DateTime.UtcNow.AddSeconds(maxRuntimeSeconds) : (DateTime?)null;
        int commented = 0;
        int succeeded = 0;
        int failed = 0;
        var baseSolution = await _workspaceManager.GetBranchedSolutionAsync(cancellationToken);

        var membersByFile = staleMembers
            .GroupBy(m => m.FilePath)
            .Select(g => g.ToList())
            .ToList();

        foreach (var fileMembers in membersByFile)
        {
            var currentFilePath = fileMembers[0].FilePath;

            // Cap/deadline checks apply per-member-slot so a file straddling the cap still processes
            // as many of its own members as fit, same budget semantics as the old per-member loop.
            var toProcess = new List<CommentingEngine.MemberSite>();
            foreach (var site in fileMembers)
            {
                if (commented >= maxMembers)
                {
                    skipped.Add(new FailureDetail { FilePath = site.FilePath, MethodName = site.MemberName, Reason = "maxMembers cap reached", Outcome = ItemRecordOutcome.Skipped });
                    FileRow(site.FilePath).Skipped++;
                    continue;
                }

                if (deadline.HasValue && DateTime.UtcNow >= deadline.Value)
                {
                    skipped.Add(new FailureDetail { FilePath = site.FilePath, MethodName = site.MemberName, Reason = "maxRuntimeSeconds cap reached", Outcome = ItemRecordOutcome.Skipped });
                    FileRow(site.FilePath).Skipped++;
                    continue;
                }

                cancellationToken.ThrowIfCancellationRequested();
                toProcess.Add(site);
                commented++;
            }

            if (toProcess.Count == 0)
            {
                continue;
            }

            var (finalText, outcomes) = await _commentingEngine.CommentFileAsync(baseSolution, currentFilePath, toProcess, DefaultMaxTokens, cancellationToken);

            var succeededSites = new HashSet<CommentingEngine.MemberSite>(outcomes.Where(o => o.Succeeded).Select(o => o.Site));
            foreach (var outcome in outcomes.Where(o => !o.Succeeded))
            {
                skipped.Add(new FailureDetail { FilePath = outcome.Site.FilePath, MethodName = outcome.Site.MemberName, Reason = outcome.FailureReason ?? "unknown failure", Outcome = ItemRecordOutcome.Failed });
                FileRow(outcome.Site.FilePath).Skipped++;
                failed++;
            }

            if (finalText == null || succeededSites.Count == 0)
            {
                continue;
            }

            var applyResult = await _workspaceManager.ApplyProposedChangesAsync(
                new Dictionary<FilePath, string> { { currentFilePath, finalText } }, validateChanges: true, cancellationToken: cancellationToken);

            if (!applyResult.Success)
            {
                var reason = applyResult.ValidationResult != null
                    ? $"apply validation failed ({applyResult.ValidationResult.Diagnostics.Count} diagnostic(s))"
                    : "apply failed";
                foreach (var site in toProcess.Where(s => succeededSites.Contains(s)))
                {
                    skipped.Add(new FailureDetail { FilePath = site.FilePath, MethodName = site.MemberName, Reason = reason, Outcome = ItemRecordOutcome.Failed });
                    FileRow(site.FilePath).Skipped++;
                    failed++;
                }
                continue;
            }

            string? beforeSource = null;
            applyResult.PreImages?.TryGetValue(currentFilePath, out beforeSource);
            foreach (var site in toProcess.Where(s => succeededSites.Contains(s)))
            {
                items.Add(new OperationItemRecord
                {
                    FilePath = site.FilePath,
                    MethodName = site.MemberName,
                    Outcome = ItemRecordOutcome.Succeeded,
                    BeforeSource = beforeSource,
                });
                FileRow(site.FilePath).Commented++;
                succeeded++;
            }
        }

        _workspaceManager.RecordBatchOutcome(succeeded, failed, rolledBack: 0, skipped: skipped.Count - failed);

        var blobName = await OperationBlobWriter.WriteAsync("bulk_comment", changeId, items, _workspaceManager.GetSolutionRoot(), cancellationToken);

        var status = _workspaceManager.GetBreakerStatus();

        return new CommentingResult
        {
            TotalMembers = totalMembers,
            AlreadyCurrent = alreadyCurrentCount,
            Seeded = seededCount,
            CommentedThisCall = succeeded,
            // Not-yet-successfully-commented members: failed/apply-failed members remain stale
            // (their [ContentHash] was never updated) same as cap-skipped ones, so a re-invoke
            // picks all of them back up via FindStaleMembersAsync.
            RemainingStale = staleMembers.Count - succeeded,
            Skipped = skipped,
            ByFile = byFile.Values.ToList(),
            Severity = status.Severity,
            BreakerOpen = status.Open,
            DryRun = false,
            BlobName = blobName,
        };
    }
}
