<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;DebugVisualStudio</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>1</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugVisualStudio|AnyCPU'">
    <WarningLevel>1</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>1</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RoslynSentinel.Common\RoslynSentinel.Common.csproj" />
    <ProjectReference Include="..\RoslynSentinel.Engines.Basic\RoslynSentinel.Engines.Basic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RoslynSentinel.Tests.Tools.Basic" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="ModelContextProtocol.Protocol" />
    <Using Include="ModelContextProtocol.Server" />
    <Using Include="RoslynSentinel.Common" />
  </ItemGroup>

</Project>
