using System.ComponentModel;
using System.Reflection;
using System.Text;
using System.Xml.Linq;

using ModelContextProtocol.Server;

using RoslynSentinel;
using RoslynSentinel.Server.Basic;
using RoslynSentinel.Tools.Basic;

namespace RoslynSentinel.Tests.Server;

/// <summary>
/// Generates architecture documentation by reflecting over MCP tool classes and their methods.
/// </summary>
public static class ArchitectureDocGenerator
{
    /// <summary>
    /// Generates the tools architecture markdown table by scanning loaded tool assemblies.
    /// </summary>
    public static string GenerateToolsMarkdown()
    {
        var sb = new StringBuilder();
        
        // Header with regeneration instructions
        sb.AppendLine("<!-- Generated by ArchitectureDocGenerator; DO NOT EDIT. Regenerate with: $env:ROSLYNSENTINEL_UPDATE_GENERATED_DOCS=1; dotnet test RoslynSentinel.Tests.Server --filter ArchitectureDocFreshness -->");
        sb.AppendLine();
        
        // Discover all tool classes and tools
        var toolsByProject = DiscoverTools();
        var unregisteredClasses = FindUnregisteredToolClasses();
        
        // Generate table per project
        foreach (var (projectName, classes) in toolsByProject.OrderBy(x => x.Key))
        {
            sb.AppendLine($"## {projectName}");
            sb.AppendLine();
            
            if (!classes.Any())
            {
                sb.AppendLine("(No tool classes in this project)");
                sb.AppendLine();
                continue;
            }
            
            // Generate table
            sb.AppendLine("| Class | Tool name | Modes | Breaker | Summary |");
            sb.AppendLine("|-------|-----------|-------|---------|---------|");
            
            foreach (var tool in classes)
            {
                var modePart = string.Join(", ", tool.Modes.OrderBy(x => x));
                var summary = EscapeMarkdownTableCell(tool.Summary);
                var breakerPart = tool.IsBreakerAllowed ? "Allowed" : "-";
                sb.AppendLine($"| {tool.ClassName} | {tool.ToolName} | {modePart} | {breakerPart} | {summary} |");
            }
            
            sb.AppendLine();
        }
        
        // Report unregistered tool classes
        if (unregisteredClasses.Any())
        {
            sb.AppendLine("## Unregistered tool classes");
            sb.AppendLine();
            sb.AppendLine("The following classes have `[McpServerToolType]` but are not registered in any mode:");
            sb.AppendLine();
            
            foreach (var className in unregisteredClasses.OrderBy(x => x))
            {
                sb.AppendLine($"- {className}");
            }
            
            sb.AppendLine();
        }
        
        return sb.ToString();
    }
    
    /// <summary>
    /// Generates the projects architecture markdown table by scanning all .csproj files.
    /// </summary>
    public static string GenerateProjectsMarkdown()
    {
        var sb = new StringBuilder();
        
        // Header with regeneration instructions
        sb.AppendLine("<!-- Generated by ArchitectureDocGenerator; DO NOT EDIT. Regenerate with: $env:ROSLYNSENTINEL_UPDATE_GENERATED_DOCS=1; dotnet test RoslynSentinel.Tests.Server --filter ArchitectureDocFreshness -->");
        sb.AppendLine();
        
        sb.AppendLine("| Project | ProjectReferences |");
        sb.AppendLine("|---------|-------------------|");
        
        // Discover all projects and their references
        var projects = DiscoverProjects();
        
        foreach (var project in projects.OrderBy(p => p.Name))
        {
            var refs = project.References.Any() 
                ? string.Join(", ", project.References.OrderBy(r => r))
                : "";
            sb.AppendLine($"| {project.Name} | {refs} |");
        }
        
        sb.AppendLine();
        
        return sb.ToString();
    }
    
    /// <summary>
    /// Discovers all tool classes and their methods, organized by project.
    /// </summary>
    private static Dictionary<string, List<ToolInfo>> DiscoverTools()
    {
        var result = new Dictionary<string, List<ToolInfo>>();
        var classToModes = ToolClassRegistry.BuildClassToModes();
        
        // Scan all assemblies
        var assemblies = new[] {
            typeof(AdminTools).Assembly, // Tools.Basic
        };
        
        // Try to load Advanced tools assembly if available
        try
        {
            assemblies = assemblies.Concat(new[] {
                Assembly.Load("RoslynSentinel.Tools.Advanced")
            }).ToArray();
        }
        catch
        {
            // Advanced assembly not available
        }
        
        // Try to load Experimental tools assembly if available
        try
        {
            assemblies = assemblies.Concat(new[] {
                Assembly.Load("RoslynSentinel.Tools.Experimental")
            }).ToArray();
        }
        catch
        {
            // Experimental assembly not available
        }
        
        foreach (var assembly in assemblies)
        {
            var projectName = assembly.GetName().Name ?? "Unknown";
            if (!result.ContainsKey(projectName))
            {
                result[projectName] = new List<ToolInfo>();
            }
            
            // Find all types with [McpServerToolType]
            var toolTypes = assembly.GetTypes()
                .Where(t => t.GetCustomAttribute<McpServerToolTypeAttribute>() != null)
                .OrderBy(t => t.Name);
            
            foreach (var toolType in toolTypes)
            {
                // Find all methods with [McpServerTool]
                var toolMethods = toolType.GetMethods(BindingFlags.Public | BindingFlags.Instance)
                    .Where(m => m.GetCustomAttribute<McpServerToolAttribute>() != null)
                    .OrderBy(m => m.Name);
                
                foreach (var method in toolMethods)
                {
                    var toolAttr = method.GetCustomAttribute<McpServerToolAttribute>();
                    var toolName = toolAttr?.Name ?? method.Name;
                    
                    var descAttr = method.GetCustomAttribute<System.ComponentModel.DescriptionAttribute>();
                    var fullDesc = descAttr?.Description ?? "";
                    var summary = TruncateSummary(fullDesc, 120);
                    
                    var modes = classToModes.TryGetValue(toolType.Name, out var m) 
                        ? m.OrderBy(x => x).ToList() 
                        : new List<string>();
                    
                    var breakerAttr = method.GetCustomAttribute<UnrecoverableBreakerAttribute>();
                    var isBreakerAllowed = breakerAttr?.Access == UnrecoverableBreakerAccess.Allowed;
                    
                    result[projectName].Add(new ToolInfo
                    {
                        ClassName = toolType.Name,
                        ToolName = toolName,
                        Modes = modes,
                        Summary = summary,
                        IsBreakerAllowed = isBreakerAllowed
                    });
                }
            }
            
            // Sort by class name then tool name
            result[projectName] = result[projectName]
                .OrderBy(t => t.ClassName)
                .ThenBy(t => t.ToolName)
                .ToList();
        }
        
        return result;
    }
    
    /// <summary>
    /// Finds tool classes that exist but are not registered in any mode.
    /// </summary>
    private static HashSet<string> FindUnregisteredToolClasses()
    {
        var registeredClasses = new HashSet<string>(StringComparer.Ordinal);
        
        // Collect all registered class names
        foreach (var classes in ToolClassRegistry.BasicModeToToolClasses.Values)
        {
            foreach (var className in classes)
            {
                registeredClasses.Add(className);
            }
        }
        
        foreach (var classes in ToolClassRegistry.AdvancedModeToToolClasses.Values)
        {
            foreach (var className in classes)
            {
                registeredClasses.Add(className);
            }
        }
        
        // Find all tool classes with [McpServerToolType] attribute
        var unregistered = new HashSet<string>(StringComparer.Ordinal);
        var assemblies = new[] {
            typeof(AdminTools).Assembly, // Tools.Basic
        };
        
        try
        {
            assemblies = assemblies.Concat(new[] {
                Assembly.Load("RoslynSentinel.Tools.Advanced")
            }).ToArray();
        }
        catch { }
        
        try
        {
            assemblies = assemblies.Concat(new[] {
                Assembly.Load("RoslynSentinel.Tools.Experimental")
            }).ToArray();
        }
        catch { }
        
        foreach (var assembly in assemblies)
        {
            var toolTypes = assembly.GetTypes()
                .Where(t => t.GetCustomAttribute<McpServerToolTypeAttribute>() != null);
            
            foreach (var toolType in toolTypes)
            {
                if (!registeredClasses.Contains(toolType.Name))
                {
                    unregistered.Add(toolType.Name);
                }
            }
        }
        
        return unregistered;
    }
    
    /// <summary>
    /// Extracts and truncates the summary from a description.
    /// </summary>
    private static string TruncateSummary(string description, int maxLength)
    {
        if (string.IsNullOrWhiteSpace(description))
            return "";
        
        // Collapse all whitespace (including newlines) to single spaces
        var text = System.Text.RegularExpressions.Regex.Replace(description, @"\s+", " ").Trim();
        
        // Find first sentence: ". " followed by capital letter, or end of text
        var sentenceMatch = System.Text.RegularExpressions.Regex.Match(text, @"^(.*?\.\s+(?=[A-Z])|.*)");
        if (sentenceMatch.Success)
        {
            text = sentenceMatch.Groups[1].Value.Trim();
        }
        
        // If still too long, truncate at last word boundary before maxLength - 3 (for "...")
        if (text.Length > maxLength)
        {
            var truncateAt = maxLength - 3;
            var lastSpace = text.LastIndexOf(' ', truncateAt);
            if (lastSpace > 0)
            {
                text = text.Substring(0, lastSpace) + "...";
            }
            else
            {
                text = text.Substring(0, truncateAt) + "...";
            }
        }
        
        return text;
    }
    
    /// <summary>
    /// Escapes pipe characters and other special markdown table characters.
    /// </summary>
    private static string EscapeMarkdownTableCell(string text)
    {
        return text.Replace("|", "\\|").Replace("\n", " ").Replace("\r", "");
    }
    
    /// <summary>
    /// Discovers all .csproj files in the repo, excluding bin/, obj/, and Worktree folders.
    /// </summary>
    private static List<ProjectInfo> DiscoverProjects()
    {
        var result = new List<ProjectInfo>();
        
        // Find repo root
        var current = AppContext.BaseDirectory;
        while (!string.IsNullOrEmpty(current))
        {
            var slnxPath = Path.Combine(current, "RoslynSentinel.slnx");
            if (File.Exists(slnxPath))
            {
                // Found repo root, search for .csproj files
                var csprojFiles = Directory.GetFiles(current, "*.csproj", SearchOption.AllDirectories)
                    .Where(f => !f.Contains("\\bin\\") && !f.Contains("\\obj\\") && !f.Contains("\\Worktree\\"))
                    .OrderBy(f => Path.GetFileName(f))
                    .ToList();
                
                foreach (var csprojPath in csprojFiles)
                {
                    var projectName = Path.GetFileNameWithoutExtension(csprojPath);
                    var refs = ExtractProjectReferences(csprojPath);
                    result.Add(new ProjectInfo { Name = projectName, References = refs });
                }
                
                break;
            }
            
            current = Path.GetDirectoryName(current);
        }
        
        return result;
    }
    
    /// <summary>
    /// Extracts ProjectReference Include names from a .csproj file using XDocument.
    /// </summary>
    private static List<string> ExtractProjectReferences(string csprojPath)
    {
        try
        {
            var doc = XDocument.Load(csprojPath);
            var ns = doc.Root?.Name.NamespaceName ?? "";
            
            var refs = doc.Descendants(XName.Get("ProjectReference", ns))
                .SelectMany(pr => pr.Attributes("Include"))
                .Select(attr => attr.Value)
                .Select(inc => Path.GetFileNameWithoutExtension(inc))
                .Distinct(StringComparer.Ordinal)
                .OrderBy(r => r)
                .ToList();
            
            return refs;
        }
        catch
        {
            return new List<string>();
        }
    }
    
    private class ToolInfo
    {
        public string ClassName { get; set; } = "";
        public string ToolName { get; set; } = "";
        public List<string> Modes { get; set; } = new();
        public string Summary { get; set; } = "";
        public bool IsBreakerAllowed { get; set; } = false;
    }
    
    private class ProjectInfo
    {
        public string Name { get; set; } = "";
        public List<string> References { get; set; } = new();
    }
}
