namespace RoslynSentinel.Common;

/// <summary>
/// Builds the source text of a self-contained <c>ContentHashAttribute</c> class to be injected
/// as a new file in a target project when the attribute is not yet present there. Mirrors
/// <c>AsyncOptimizationEngine.BuildMigrationCandidateAttributeSource</c>: global namespace,
/// <c>internal sealed</c>, no compilation needed to inject.
/// </summary>
public static class ContentHashAttributeSource
{
    public const string ShortName = "ContentHash";
    public const string FullName = "ContentHashAttribute";

    /// <summary>Sentinel hash written by the seed pass — never a real SHA-256 output, so it always compares unequal to a computed hash.</summary>
    public const string SeedHash = "00000000";

    /// <summary>
    /// Complete C# source for the attribute class file. Global namespace — do NOT add a
    /// 'namespace' wrapper (SDK-style projects that glob-include multiple subdirectories would
    /// otherwise see ambiguous copies if the type were namespaced per-folder).
    /// </summary>
    public static string BuildSource()
    {
        return
@"using System;

// ── ContentHashAttribute ────────────────────────────────────────────────────
// Auto-generated by RoslynSentinel BulkComment tools.
// Global namespace — do NOT add a 'namespace' wrapper.
// Place exactly ONE copy of this file at the project root (.csproj directory)
// so that SDK-style glob-includes find it without duplication.

/// <summary>
/// Records a content hash for a member, tagged by purpose, so tooling can detect whether the
/// member's source has changed since it was last processed for that purpose (e.g. commenting).
/// </summary>
/// <remarks>
/// Purpose is free text at this syntax-text layer, but constrained by RoslynSentinel's
/// ContentHashPurpose enum in the engine that reads/writes these attributes. AllowMultiple lets
/// unrelated tools tag the same member under different purposes without collision.
/// </remarks>
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Constructor | AttributeTargets.Property | AttributeTargets.Enum, AllowMultiple = true, Inherited = false)]
internal sealed class ContentHashAttribute : Attribute
{
    /// <summary>Initialises a new <see cref=""ContentHashAttribute""/>.</summary>
    /// <param name=""purpose"">The tag identifying why this hash was recorded (e.g. ""Comment"").</param>
    /// <param name=""hash"">Truncated SHA-256 of the member's normalized source text.</param>
    public ContentHashAttribute(string purpose, string hash)
    {
        Purpose = purpose;
        Hash = hash;
    }

    /// <summary>The tag identifying why this hash was recorded.</summary>
    public string Purpose { get; }

    /// <summary>Truncated SHA-256 of the member's normalized source text.</summary>
    public string Hash { get; }
}
";
    }
}
